version: "3.9"
services:
  postgres:
    container_name: container_name
    image: postgres
    environment:
      POSTGRES_DB: "db_postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
